assembler:
	gcc assembler.c parser.c lexer2.c -o assembler -W -Wall -Wextra

compilador:
	gcc compilador.c ./utils/arvore.c -o compilador -W -Wall -Wextra

neander:
	gcc -W -Wall -pedantic -std=c99 neander.c -o neander